seed: 8888

data:
  name: ffhq
  root: ~/data/FFHQ/
  img_size: 256

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

transformer:
  target: models.stage2.transformer.MaskTransformer
  params:
    vocab_size: 8192
    embed_dim: 768
    n_heads: 8
    n_layers: 12
    n_tokens: 256
    n_classes: 0
    dropout: 0.1
    mask_schedule_type: cosine

vqmodel:
  model_name: amused/amused-256


train:
  n_steps: 500000
  batch_size: 256

  label_smoothing: 0.1

  print_freq: 100
  save_freq: 50000
  sample_freq: 5000
  n_samples: 16

  optim:
    target: torch.optim.AdamW
    params:
      lr: 0.0001
      betas: [0.9, 0.96]
      weight_decay: 0.045
