seed: 8888

data:
  name: imagenet
  root: ~/data/ImageNet/ILSVRC2012/Images
  img_size: 256
  crop: center
  n_classes: 1000

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

vqmodel:
  model_name: maskgit-vqgan-imagenet-f16-256

transformer:
  target: models.stage2.transformer.MaskTransformer
  params:
    vocab_size: 1024
    embed_dim: 768
    n_heads: 8
    n_layers: 24
    n_tokens: 256
    n_classes: 1000
    dropout: 0.1
    mask_schedule_type: cosine


train:
  n_steps: 1500000
  batch_size: 256
  micro_batch_size: ~

  label_smoothing: 0.1
  cond_drop_prob: 0.1
  clip_grad_norm: 1.0

  ema:
    decay: 0.9999
    ema_warmup_type: crowsonkb

  print_freq: 100
  save_freq: 50000
  sample_freq: 5000
  n_samples_per_class: 5
  sample_class_ids: [88, 279, 388, 417, 980]

  optim:
    target: torch.optim.AdamW
    params:
      lr: 0.0001
      betas: [0.9, 0.96]
      weight_decay: 0.045

  sched:
    target: utils.scheduler.CosineWarmupLR
    params:
      warmup_steps: 5000
      training_steps: 1500000
